kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: bastion-vhnwk.vhnwk.dynamic.opentlc.com/mirror/oc-mirror-metadata
    skipTLS: true
mirror:
  platform:
    architectures:
      - "multi"
      - "amd64"
    channels:
    - name: stable-4.15
      minVersion: 4.15.0
      maxVersion: 4.15.0
      type: ocp
